language: node_js

node_js:
  - stable

dist: trusty

sudo: false

cache:
  npm: true
  directories:
    - node_modules

before_script:
  - greenkeeper-lockfile-update
  - yarn test:coverage

script:
  - yarn build

after_script:
  - greenkeeper-lockfile-upload
